apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 853461024761.dkr.ecr.us-east-1.amazonaws.com/backend-ventas:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "mysql-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "appdb"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15