name: CI/CD - Backend

on:
  push:
    branches: [ "deploy" ] # se ejecuta al hacer push a la rama deploy

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imágenes Backend y push a ECR
      run: |
        docker build -f ./back-Despachos_SpringBoot/Dockerfile -t back-despachos ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker tag back-despachos:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:despachos
        
        docker build -f ./back-Ventas_SpringBoot/Dockerfile -t back-ventas ./back-Ventas_SpringBoot/Springboot-API-REST
        docker tag back-ventas:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar microservicios de backend con Docker Compose" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "mkdir -p ~/app-backend && cd ~/app-backend",
            "curl -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/deploy/docker-compose.yml",
            "/usr/libexec/docker/cli-plugins/docker-compose pull",
            "/usr/libexec/docker/cli-plugins/docker-compose up -d",
            "docker image prune -f"
          ]}' \
          --output text